Chromakey can standby when there's no readers
- allows it to be running continually in the background
  without showing the webcam as in use the whole time

diff --git a/bin/chromakey b/bin/chromakey
--- a/bin/chromakey
+++ b/bin/chromakey
@@ -25,8 +25,16 @@ CMD_DIR="$(cd "$(dirname "$CMD")" && pwd -P)"
 [ "$SIMILARITY" ] || SIMILARITY=0.16
 [ "$BLEND" ] || BLEND=0.01
 [ "$CAMERA" ] || CAMERA=/dev/video4
-[ "$OUTPUT" ] || OUTPUT=/dev/video6
+[ "$DEVICE_NUMBER" ] || DEVICE_NUMBER="6"
+[ "$OUTPUT" ] || OUTPUT="/dev/video${DEVICE_NUMBER}"
 [ "$FRAME_RATE" ] || FRAME_RATE=30
+
+# Basic helpers
+out() { echo "$(date +%Y%m%dT%H%M%SZ): $*"; }
+err() { out "$*" 1>&2; }
+vrb() { [ ! "$VERBOSE" ] || out "$@"; }
+dbg() { [ ! "$DEBUG" ] || err "$@"; }
+die() { err "EXIT: $1" && [ "$2" ] && [ "$2" -ge 0 ] && exit "$2" || exit 1; }
 
 # Show help function to be used below
 show_help() {
@@ -43,31 +51,37 @@ show_help() {
 	echo "Copyright (c) <Steven Varga 2010-2021> <steven@vargaconsulting.ca, Toronto, On>"
 }
 
-#/bin/bash
+function finish {
+	# Your cleanup code here
+	if [ -n "${PID}" ]; then # streamer is already running
+		dbg "--- Stopping chromakey"
+		kill "${PID}" && sleep 2 || true
+	fi
+	dbg "--- Removing loaded v4l2loopback dkms"
+	sudo modprobe -r v4l2loopback
+}
+trap finish EXIT
 
-# testing webrtc with firefox (google chrome doesn't pick up the pseudo device)
-# https://webrtc.github.io/samples/src/content/devices/input-output/
+load_module() {
+	dbg "--- Loading v4l2loopback with device ${DEVICE_FILE}"
+	sudo modprobe v4l2loopback video_nr="${DEVICE_NUMBER}" exclusive_caps=1 card_label="green-screen"
+}
 
-#
-# tape mic to throat, sound level 30%
-#
-#
-# install and set up pseudo device
-# sudo apt install v4l2loopback-utils v4l2loopback-dkms
-# sudo modprobe v4l2loopback # creates pseudo device probably /dev/video1
-#
-# captures
+reload_v4l2() {
+	sudo modprobe -r v4l2loopback
+	load_module
+}
 
-if [ ! -f /dev/video6 ]; then
-	sudo modprobe v4l2loopback video_nr=6 exclusive_caps=1 card_label="green-screen"
-fi
-
-# Basic helpers
-out() { echo "$(date +%Y%m%dT%H%M%SZ): $*"; }
-err() { out "$*" 1>&2; }
-vrb() { [ ! "$VERBOSE" ] || out "$@"; }
-dbg() { [ ! "$DEBUG" ] || err "$@"; }
-die() { err "EXIT: $1" && [ "$2" ] && [ "$2" -ge 0 ] && exit "$2" || exit 1; }
+start_camera() {
+	dbg "Starting camera"
+	ffmpeg $LOGLEVEL -hide_banner \
+		-video_size $SIZE -framerate $FRAME_RATE -i $IMAGE \
+		-f v4l2 -pix_fmt yuyv422 -framerate $FRAME_RATE -video_size $SIZE -i $CAMERA \
+		-filter_complex "[0:v]scale=1280:720[imout];[1:v]crop=x=175:y=181:w=893:h=539,chromanr,chromakey=$KEY:$SIMILARITY:$BLEND[ckout];[imout][ckout]overlay=x=387:y=181" \
+		-pix_fmt yuyv422 -f v4l2 $OUTPUT &
+	PID="${!}"
+	dbg " - camera started with PID ${PID}"
+}
 
 # Parse command line options (odd formatting to simplify show_help() above)
 NARGS=-1
@@ -102,6 +116,10 @@ while [ "$#" -ne "$NARGS" ]; do
 		shift && X_POS="$1" && shift && vrb "#-INFO: X_POS=$X_POS" ;;
 	-y | --y_pos) # xgrab: y position  (DEFAULT: $Y_POS)
 		shift && Y_POS="$1" && shift && vrb "#-INFO: Y_POS=$Y_POS" ;;
+	-reload | --reload) # reload v4l2 driver then exit
+		reload_v4l2
+		exit 0
+		;;
 		# END SWITCHES
 	esac
 done
@@ -113,6 +131,38 @@ done
 # LOGLEVEL="-loglevel debug"
 LOGLEVEL=
 
+if [ ! -f /dev/video6 ]; then
+	load_module
+	dbg "--- Locking output format"
+	sudo v4l2-ctl --device "${OUTPUT}" --set-ctrl keep_format=1
+	start_camera
+	sleep 5
+
+	dbg "--- Setting device timeout (blank video if connection is lost)"
+	sudo v4l2-ctl --device "${OUTPUT}" --set-ctrl timeout=1500
+fi
+
+# Trigger usage check in 1 second so that if the camera is not used the streamer will stop
+(
+	sleep 1
+	touch "${OUTPUT}"
+) &
+
+dbg "--- Waiting for video device usage"
+sudo inotifywait -e OPEN,CLOSE -m "${OUTPUT}" |
+	while read dir op file; do
+		if [ -n "${PID}" ]; then                                                  # streamer is already running
+			if [ "$(lsof -t "${OUTPUT}" | grep -v "${PID}" | wc -l)" -eq "0" ]; then # no more clients
+				echo "--- No more clients, stopping green screen"
+				kill "${PID}"
+				unset PID
+			fi
+		elif [ "$(lsof -t "${OUTPUT}" | wc -l)" -gt "0" ]; then # new clients
+			echo "--- Detected usage of camera, spinning up green screen"
+			start_camera
+		fi
+	done
+
 # SETTINGS FROM OBS STUDIO:
 # Video crop:
 # - Position: 387, 181
@@ -122,20 +172,77 @@ LOGLEVEL=
 # - Smoothness: 75 / 1000
 # - Spill reduction: 1 / 1000
 
-if [ -z "$IMAGE" ]; then
-	ffmpeg -hide_banner -video_size $SIZE -framerate $FRAME_RATE \
-		-f x11grab -i :0.0+$X_POS,$Y_POS \
-		-f v4l2 -pix_fmt yuyv422 -framerate $FRAME_RATE -video_size $SIZE -i $CAMERA -filter_complex \
-		"[1:v]hflip,chromakey=$KEY:$SIMILARITY:$BLEND[ckout];[0:v][ckout]overlay" \
-		-pix_fmt yuyv422 -f v4l2 $OUTPUT
-else
-	ffmpeg $LOGLEVEL -hide_banner \
-		-video_size $SIZE -framerate $FRAME_RATE -i $IMAGE \
-		-f v4l2 -pix_fmt yuyv422 -framerate $FRAME_RATE -video_size $SIZE -i $CAMERA \
-		-filter_complex "[0:v]scale=1280:720[imout];[1:v]crop=x=175:y=181:w=893:h=539,chromakey=$KEY:$SIMILARITY:$BLEND[ckout];[imout][ckout]overlay=x=387:y=181" \
-		-pix_fmt yuyv422 -f v4l2 $OUTPUT
-fi
+# if [ -z "$IMAGE" ]; then
+# 	ffmpeg -hide_banner -video_size $SIZE -framerate $FRAME_RATE \
+# 		-f x11grab -i :0.0+$X_POS,$Y_POS \
+# 		-f v4l2 -pix_fmt yuyv422 -framerate $FRAME_RATE -video_size $SIZE -i $CAMERA -filter_complex \
+# 		"[1:v]hflip,chromakey=$KEY:$SIMILARITY:$BLEND[ckout];[0:v][ckout]overlay" \
+# 		-pix_fmt yuyv422 -f v4l2 $OUTPUT
+# else
+
+# fi
 #https://ffmpeg.org/ffmpeg-filters.html#pad-1
 #crop=x=175:y=212:w=893:h=539
 #overlay=x=387:y=181
 #chromakey=$KEY:$SIMILARITY:$BLEND,
+
+#####################################################
+# Attempt to standby camera until a reader connects #
+#####################################################
+
+# https://gist.github.com/iddo/a4c03c63c055064a0657d0d36a9f667d
+
+#!/usr/bin/env bash
+# set -e
+
+# DEVICE_NUMBER="9"
+# DEVICE_FILE="/dev/video${DEVICE_NUMBER}"
+# RTSP_URL="rtsp://username:password@WIFIFCAM:554"
+
+# function finish {
+# 	# Your cleanup code here
+# 	if [ -n "${PID}" ]; then # streamer is already running
+# 		echo "--- Stopping RTSP streamer"
+# 		kill "${PID}" && sleep 2 || true
+# 	fi
+# 	echo "--- Removing loaded v4l2loopback dkms"
+# 	sudo modprobe -r v4l2loopback
+# }
+# trap finish EXIT
+
+# if [ ! -e "${DEVICE_FILE}" ]; then
+
+# 	echo "--- Loading v4l2loopback with device ${DEVICE_FILE}"
+# 	sudo modprobe v4l2loopback exclusive_caps=1 video_nr=${DEVICE_NUMBER} card_label="Wifi Security Camera"
+
+# 	echo "--- Locking output format"
+# 	sudo v4l2-ctl --device "${DEVICE_FILE}" --set-ctrl keep_format=1
+# 	ffmpeg -rtsp_transport tcp -i "${RTSP_URL}" -f v4l2 "${DEVICE_FILE}" &
+# 	PID="${!}"
+# 	echo "--- PID of ffmpeg is '${PID}'"
+# 	sleep 5
+
+# 	echo "--- Setting device timeout (blank video if connection is lost)"
+# 	sudo v4l2-ctl --device "${DEVICE_FILE}" --set-ctrl timeout=1500
+# fi
+
+# # Trigger usage check in 1 second so that if the camera is not used the streamer will stop
+# (sleep 1; touch "${DEVICE_FILE}")&
+
+# echo "--- Waiting for video device usage"
+# sudo inotifywait -e OPEN,CLOSE -m "${DEVICE_FILE}" |
+# while read dir op file; do
+# 	if [ -n "${PID}" ]; then # streamer is already running
+# 		if [ "$(lsof -t "${DEVICE_FILE}" | grep -v "${PID}" | wc -l)" -eq "0" ]; then # no more clients
+# 			echo "--- No more clients, stopping RTSP streamer"
+# 			kill "${PID}"
+# 			unset PID
+# 		fi
+# 	elif [ "$(lsof -t "${DEVICE_FILE}" | wc -l)" -gt "0" ]; then # new clients
+# 		echo "--- Detected usage of camera, spinning up RTSP streamer"
+# 		ffmpeg -rtsp_transport tcp -i "${RTSP_URL}" -vf format=pix_fmts=yuv420p -f v4l2 "${DEVICE_FILE}" &
+# 		# TODO add disconnection detection and restart streamer
+# 		PID="${!}"
+# 		echo "--- PID of ffmpeg is '${PID}'"
+# 	fi
+# done
